---
replicas: 1

image:
  repository: arnaudmorin/demo-flask
  tag: "latest"

service:
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  host: demo.local

# An empty catApiUrl will prevent changing the default CAT_API_URL on the app
catApiUrl: ""
